import type { Vehicle } from '@/types/inventory';

// Mock inventory data for development
export const mockInventory: Vehicle[] = [
  {
    vin: '1HGCV1F31MA123456',
    stock_no: 'H24001',
    inventory_type: 'new',
    price: 28995,
    msrp: 30450,
    dom: 12,
    build: {
      year: 2024,
      make: 'Honda',
      model: 'Accord',
      trim: 'LX',
      body_style: 'Sedan',
      engine: '1.5L Turbo',
      transmission: 'CVT',
      drivetrain: 'FWD',
      exterior_color: 'Platinum White Pearl',
      interior_color: 'Black',
    },
    residuals: { 24: 19488, 36: 16748, 39: 15834, 48: 13703 },
    financeRates: {
      excellent: 4.99,
      good: 6.99,
      fair: 9.99,
      poor: 14.99,
    },
    isAged: false,
    eligibleIncentives: [
      {
        id: 'honda-finance-bonus',
        type: 'finance',
        name: 'Honda Finance Bonus',
        amount: 500,
        requirements: ['honda_financial'],
      },
      {
        id: 'lease-bonus',
        type: 'lease',
        name: 'Lease Bonus Cash',
        amount: 1500,
        requirements: ['honda_financial'],
      },
    ],
  },
  {
    vin: '5FNYF6H76NB123456',
    stock_no: 'H24002',
    inventory_type: 'new',
    price: 39995,
    msrp: 42100,
    dom: 34,
    build: {
      year: 2024,
      make: 'Honda',
      model: 'Pilot',
      trim: 'Sport',
      body_style: 'SUV',
      engine: '3.5L V6',
      transmission: '9-Speed Automatic',
      drivetrain: 'AWD',
      exterior_color: 'Steel Sapphire Metallic',
      interior_color: 'Gray',
    },
    residuals: { 24: 26944, 36: 23155, 39: 21892, 48: 18945 },
    financeRates: {
      excellent: 4.99,
      good: 6.99,
      fair: 9.99,
      poor: 14.99,
    },
    isAged: false,
    eligibleIncentives: [
      {
        id: 'honda-finance-bonus',
        type: 'finance',
        name: 'Honda Finance Bonus',
        amount: 500,
        requirements: ['honda_financial'],
      },
      {
        id: 'lease-bonus',
        type: 'lease',
        name: 'Lease Bonus Cash',
        amount: 1500,
        requirements: ['honda_financial'],
      },
    ],
  },
  {
    vin: '7FARW2H91RE123456',
    stock_no: 'H24003',
    inventory_type: 'new',
    price: 31495,
    msrp: 32900,
    dom: 67,
    build: {
      year: 2024,
      make: 'Honda',
      model: 'CR-V',
      trim: 'EX',
      body_style: 'SUV',
      engine: '1.5L Turbo',
      transmission: 'CVT',
      drivetrain: 'AWD',
      exterior_color: 'Radiant Red Metallic',
      interior_color: 'Black',
    },
    residuals: { 24: 21056, 36: 18095, 39: 17108, 48: 14805 },
    financeRates: {
      excellent: 4.99,
      good: 6.99,
      fair: 9.99,
      poor: 14.99,
    },
    isAged: true,
    eligibleIncentives: [
      {
        id: 'honda-finance-bonus',
        type: 'finance',
        name: 'Honda Finance Bonus',
        amount: 500,
        requirements: ['honda_financial'],
      },
      {
        id: 'lease-bonus',
        type: 'lease',
        name: 'Lease Bonus Cash',
        amount: 1500,
        requirements: ['honda_financial'],
      },
      {
        id: 'aged-inventory',
        type: 'cash',
        name: 'Aged Inventory Discount',
        amount: 1000,
        stackable: true,
      },
    ],
  },
  {
    vin: 'JHMZE4H78PS123456',
    stock_no: 'H24004',
    inventory_type: 'new',
    price: 24995,
    msrp: 26395,
    dom: 22,
    build: {
      year: 2024,
      make: 'Honda',
      model: 'Civic',
      trim: 'Sport',
      body_style: 'Sedan',
      engine: '2.0L',
      transmission: 'CVT',
      drivetrain: 'FWD',
      exterior_color: 'Sonic Gray Pearl',
      interior_color: 'Black',
    },
    residuals: { 24: 16893, 36: 14517, 39: 13725, 48: 11878 },
    financeRates: {
      excellent: 4.99,
      good: 6.99,
      fair: 9.99,
      poor: 14.99,
    },
    isAged: false,
    eligibleIncentives: [
      {
        id: 'honda-finance-bonus',
        type: 'finance',
        name: 'Honda Finance Bonus',
        amount: 500,
        requirements: ['honda_financial'],
      },
    ],
  },
  {
    vin: '5J6RM4H98PL123456',
    stock_no: 'H24005',
    inventory_type: 'new',
    price: 36995,
    msrp: 38650,
    dom: 91,
    build: {
      year: 2024,
      make: 'Honda',
      model: 'Passport',
      trim: 'TrailSport',
      body_style: 'SUV',
      engine: '3.5L V6',
      transmission: '9-Speed Automatic',
      drivetrain: 'AWD',
      exterior_color: 'Lunar Silver Metallic',
      interior_color: 'Black/Orange',
    },
    residuals: { 24: 24736, 36: 21258, 39: 20098, 48: 17393 },
    financeRates: {
      excellent: 4.99,
      good: 6.99,
      fair: 9.99,
      poor: 14.99,
    },
    isAged: true,
    eligibleIncentives: [
      {
        id: 'honda-finance-bonus',
        type: 'finance',
        name: 'Honda Finance Bonus',
        amount: 500,
        requirements: ['honda_financial'],
      },
      {
        id: 'passport-cash',
        type: 'cash',
        name: 'Passport Bonus Cash',
        amount: 1000,
        stackable: true,
      },
      {
        id: 'aged-inventory',
        type: 'cash',
        name: 'Aged Inventory Discount',
        amount: 1500,
        stackable: true,
      },
    ],
  },
  {
    vin: '2HGFC2F59PH123456',
    stock_no: 'H23006',
    inventory_type: 'used',
    price: 22995,
    msrp: 24000,
    dom: 45,
    build: {
      year: 2023,
      make: 'Honda',
      model: 'Civic',
      trim: 'Si',
      body_style: 'Sedan',
      engine: '1.5L Turbo',
      transmission: '6-Speed Manual',
      drivetrain: 'FWD',
      exterior_color: 'Rallye Red',
      interior_color: 'Black/Red',
    },
    financeRates: {
      excellent: 5.99,
      good: 7.99,
      fair: 11.99,
      poor: 17.99,
    },
    isAged: false,
  },
  {
    vin: 'KM8K3CA73PU123456',
    stock_no: 'H24007',
    inventory_type: 'new',
    price: 43995,
    msrp: 45900,
    dom: 15,
    build: {
      year: 2024,
      make: 'Honda',
      model: 'Odyssey',
      trim: 'Elite',
      body_style: 'Minivan',
      engine: '3.5L V6',
      transmission: '10-Speed Automatic',
      drivetrain: 'FWD',
      exterior_color: 'Pacific Pewter Metallic',
      interior_color: 'Beige',
    },
    residuals: { 24: 29376, 36: 25245, 39: 23868, 48: 20655 },
    financeRates: {
      excellent: 4.99,
      good: 6.99,
      fair: 9.99,
      poor: 14.99,
    },
    isAged: false,
    eligibleIncentives: [
      {
        id: 'honda-finance-bonus',
        type: 'finance',
        name: 'Honda Finance Bonus',
        amount: 500,
        requirements: ['honda_financial'],
      },
    ],
  },
  {
    vin: '1HGCV2F88PA123456',
    stock_no: 'H24008',
    inventory_type: 'new',
    price: 34495,
    msrp: 36100,
    dom: 28,
    build: {
      year: 2024,
      make: 'Honda',
      model: 'Accord',
      trim: 'Touring',
      body_style: 'Sedan',
      engine: '2.0L Turbo',
      transmission: '10-Speed Automatic',
      drivetrain: 'FWD',
      exterior_color: 'Obsidian Blue Pearl',
      interior_color: 'Ivory',
    },
    residuals: { 24: 23104, 36: 19855, 39: 18772, 48: 16245 },
    financeRates: {
      excellent: 4.99,
      good: 6.99,
      fair: 9.99,
      poor: 14.99,
    },
    isAged: false,
    eligibleIncentives: [
      {
        id: 'honda-finance-bonus',
        type: 'finance',
        name: 'Honda Finance Bonus',
        amount: 500,
        requirements: ['honda_financial'],
      },
      {
        id: 'lease-bonus',
        type: 'lease',
        name: 'Lease Bonus Cash',
        amount: 1500,
        requirements: ['honda_financial'],
      },
    ],
  },
];